apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service-service
  labels:
    app.kubernetes.io/name: ui-service-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ui-service-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ui-service-service
    spec:
      containers:
        - name: ui-service-service
          image: petrolingus/ui-service:latest
          imagePullPolicy: Always
          env:
            - name: PROCESS_SERVICE
              value: http://process-service
            - name: RETRY_DELAY
              value: '10'
            - name: READ_TIMEOUT
              value: '5000'
          ports:
            - containerPort: 8080