apiVersion: apps/v1
kind: Deployment
metadata:
  name: process-service
  labels:
    app.kubernetes.io/name: process-service
spec:
  replicas: 16
  selector:
    matchLabels:
      app.kubernetes.io/name: process-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: process-service
    spec:
      containers:
        - name: process-service
          image: petrolingus/process-service:latest
          imagePullPolicy: Always
          env:
            - name: BREAKDOWN_PROBABILITY
              value: '-1'
            - name: IS_COLORED
              value: 'false'
          ports:
            - containerPort: 8080
              protocol: TCP
#          resources:
#            requests:
#              cpu: "250m"
#              memory: "512Mi"
#            limits:
#              cpu: "250m"
#              memory: "512Mi"