apiVersion: apps/v1
kind: Deployment
metadata:
  name: process-service
  labels:
    app.kubernetes.io/name: process-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: process-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: process-service
    spec:
      containers:
        - name: process-service
          image: petrolingus/process-service:latest
          imagePullPolicy: Always
          env:
            - name: SYSTEM_EXIT_PROBABILITY
              value: '0.1'
          ports:
            - containerPort: 8080
              protocol: TCP
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: main-ingress
##  annotations:
##    nginx.ingress.kubernetes.io/load-balance: round_robin
##    nginx.org/lb-method: round_robin
##    nginx.org/server-snippets: |
##      http {
##        upstream processapp {
##          server process.example.com;
##        }
##        server {
##            listen 80;
##            location / {
##              proxy_pass http://processapp;
##            }
##        }
##      }
#spec:
#  ingressClassName: nginx
#  rules:
#    - host: process.example.com
#      http:
#        paths:
#          - pathType: Prefix
#            path: /
#            backend:
#              service:
#                name: process-service-svc
#                port:
#                  number: 80