apiVersion: v1
kind: Service
metadata:
  name: process-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: process-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080