apiVersion: v1
kind: Service
metadata:
  name: process-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: process-service
  ports:
    - name: web
      port: 8080
      targetPort: 8080
      protocol: TCP
